name: PR

on:
    pull_request:
        types: [ opened, ready_for_review, reopened ]

jobs:
    auto_request_review:
        runs-on: ubuntu-latest

        steps:
            -   name: Auto Request Review
                uses: kentaro-m/auto-assign-action@v1.2.6
                with:
                    configuration-path: .github/auto_assign.yml
                    repo-token: "${{ secrets.GH_API_TOKEN }}"
