name: PR

on:
    pull_request:
        types: [ opened, edited, closed, reopened ]

jobs:
    check_dependencies:
        runs-on: ubuntu-latest

        steps:
            -   name: Check dependencies
                uses: gregsdennis/dependencies-action@1.3.0
                env:
                    GITHUB_TOKEN: ${{ secrets.GH_API_TOKEN }}
